// flow-typed signature: faa69b0553f93d63d6d59c2eee2dede8
// flow-typed version: <<STUB>>/@monaco-editor/react_v^3.0.1/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@monaco-editor/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@monaco-editor/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@monaco-editor/react/lib/config' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/config/themes' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/ControlledEditor/ControlledEditor' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/ControlledEditor' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/DiffEditor/DiffEditor' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/DiffEditor' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/DiffEditor/styles' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/Editor/Editor' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/Editor' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/Editor/styles' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/Loading' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/Loading/Loading' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/MonacoContainer' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/MonacoContainer/MonacoContainer' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/MonacoContainer/styles' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/utils/deepMerge' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/utils/hooks' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/utils/hooks/useMount' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/utils/hooks/useUpdate' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/utils' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/utils/monaco' {
  declare module.exports: any;
}

declare module '@monaco-editor/react/lib/utils/noop' {
  declare module.exports: any;
}

// Filename aliases
declare module '@monaco-editor/react/lib/config/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/config'>;
}
declare module '@monaco-editor/react/lib/config/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/config'>;
}
declare module '@monaco-editor/react/lib/config/themes.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/config/themes'>;
}
declare module '@monaco-editor/react/lib/ControlledEditor/ControlledEditor.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/ControlledEditor/ControlledEditor'>;
}
declare module '@monaco-editor/react/lib/ControlledEditor/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/ControlledEditor'>;
}
declare module '@monaco-editor/react/lib/ControlledEditor/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/ControlledEditor'>;
}
declare module '@monaco-editor/react/lib/DiffEditor/DiffEditor.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/DiffEditor/DiffEditor'>;
}
declare module '@monaco-editor/react/lib/DiffEditor/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/DiffEditor'>;
}
declare module '@monaco-editor/react/lib/DiffEditor/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/DiffEditor'>;
}
declare module '@monaco-editor/react/lib/DiffEditor/styles.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/DiffEditor/styles'>;
}
declare module '@monaco-editor/react/lib/Editor/Editor.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/Editor/Editor'>;
}
declare module '@monaco-editor/react/lib/Editor/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/Editor'>;
}
declare module '@monaco-editor/react/lib/Editor/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/Editor'>;
}
declare module '@monaco-editor/react/lib/Editor/styles.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/Editor/styles'>;
}
declare module '@monaco-editor/react/lib/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib'>;
}
declare module '@monaco-editor/react/lib/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib'>;
}
declare module '@monaco-editor/react/lib/Loading/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/Loading'>;
}
declare module '@monaco-editor/react/lib/Loading/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/Loading'>;
}
declare module '@monaco-editor/react/lib/Loading/Loading.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/Loading/Loading'>;
}
declare module '@monaco-editor/react/lib/MonacoContainer/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/MonacoContainer'>;
}
declare module '@monaco-editor/react/lib/MonacoContainer/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/MonacoContainer'>;
}
declare module '@monaco-editor/react/lib/MonacoContainer/MonacoContainer.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/MonacoContainer/MonacoContainer'>;
}
declare module '@monaco-editor/react/lib/MonacoContainer/styles.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/MonacoContainer/styles'>;
}
declare module '@monaco-editor/react/lib/utils/deepMerge.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/deepMerge'>;
}
declare module '@monaco-editor/react/lib/utils/hooks/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/hooks'>;
}
declare module '@monaco-editor/react/lib/utils/hooks/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/hooks'>;
}
declare module '@monaco-editor/react/lib/utils/hooks/useMount/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/hooks/useMount'>;
}
declare module '@monaco-editor/react/lib/utils/hooks/useMount/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/hooks/useMount'>;
}
declare module '@monaco-editor/react/lib/utils/hooks/useUpdate/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/hooks/useUpdate'>;
}
declare module '@monaco-editor/react/lib/utils/hooks/useUpdate/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/hooks/useUpdate'>;
}
declare module '@monaco-editor/react/lib/utils/index' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils'>;
}
declare module '@monaco-editor/react/lib/utils/index.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils'>;
}
declare module '@monaco-editor/react/lib/utils/monaco.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/monaco'>;
}
declare module '@monaco-editor/react/lib/utils/noop.js' {
  declare module.exports: $Exports<'@monaco-editor/react/lib/utils/noop'>;
}
